//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryTools.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lottery
    {
        public int ID { get; set; }
        public int RED1 { get; set; }
        public int RED2 { get; set; }
        public int RED3 { get; set; }
        public int RED4 { get; set; }
        public int RED5 { get; set; }
        public int RED6 { get; set; }
        public int BLUE { get; set; }
        public int TOTAL { get; set; }
        public int AVERAGE { get; set; }
        public int ODD { get; set; }
        public int EVEN { get; set; }
        public string RKEY { get; set; }
        public string WKEY { get; set; }
        public System.DateTime DATE { get; set; }
        public int RAVERAGE { get; set; }
        public int RTOTAL { get; set; }
    }
}
